language: node_js
node_js:
- '7'
script:
- node parsers/Languages.js
after_success:
- .travis/push.sh
env:
  global:
    secure: CB71wEr8cmcoFb/TXJZqBT/fjQEQUK1SnQH6IOYQ17HPTa+lxeAFw1B43O7jtgXu8nFwldbQysh2n1OpEUAP5dlFxiQPXoRLSuFL86CD3lpCQa7+ChkrYi7zTpz8ssXQ25Noj7+Mn5gVLivcpmaNcDQyw32b6kZnJW2FHesxgLpKpU0mO54duHKHXEUeTSe4M7nTKXgGTinnuIfkHB1QBPeVmmbW8v7k/jR9kQb67vSBfCdpzstBi7a6wB1vHnRY41mBVe97TOXrEfLueGb0pAqLFxAUJkr5iy9GkguhBi7AZz2XAa3libMpB768FRrSCaXEydw4zZInwfRB5OR1txgtT0PEoySgfjy1e+IaMbTJQYlw99PD/UagRcz/NSzP+UqsPRelKg9IdDKMcOYWiQZOBE+Www/G3hk7Xr8bLum6OVgB/ze2pZ53OZVspWGCUpk48X31Ki+mmJJWa7Rk814VGsTt459gsMjv1iCT6FqDK7RGUPB5nDxMN+Jn0wE35Dc8f0uMjk8MRObH5d7kOIdBcuDsKZYkYJ3PK807tVU5pOSsTKYt48vb7iwMnRtNAptRr0Icc6eQZQeqcmSgKCu8lVm0pRwi4ygaTi+NbHZ6gpJzZXNoHt9Sk97RLTC2eHzSBbjX9w0/IkXZIYHYBfQsQdz4ohIaWdfn2C9DRYY=
